### ISSUE TITLE
test集pids都设为1，训练过程中的accuracy是怎么得来的呢

### ISSUE THREAD

**Issue by zhangting1994** [heshuting555/NAIC_Person_ReID_DMT#7]

**Comment by heshuting555** [comment]
训练的acc是针对训练过程的label呢，测试过程因为没有ground truth所以都置为1。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhangting <notifications@github.com&gt;
发送时间: 2020年9月27日 16:10
收件人: heshuting555/NAIC_Person_ReID_DMT <NAIC_Person_ReID_DMT@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[heshuting555/NAIC_Person_ReID_DMT] test集pids都设为1，训练过程中的accuracy是怎么得来的呢 (#7)

**Comment by zhangting1994** [comment]
=> NAIC Competition data loaded
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    | 15506 |    68672 |         1
  query    |     1 |     2900 |         1
  gallery  |     1 |    40466 |         1
  ----------------------------------------
using resnet101_ibn_a as a backbone
Loading pretrained ImageNet model......from ./imagenet_models/resnet101_ibn_a.pth.tar
using arcface with s:30, m: 0.4
Traceback (most recent call last):
  File "test.py", line 44, in <module>
    model.load_param(cfg.TEST.WEIGHT)
  File "/data/zhangting/NAIC_Person_ReID_DMT/model/make_model.py", line 157, in load_param
    self.state_dict()[i].copy_(param_dict[i])
KeyError: 'module.base.conv1.weight'
请问这个报错是怎么回事呢

**Comment by ZersTorerr** [comment]
> ## => NAIC Competition data loaded
> Dataset statistics:
> ## subset | # ids | # images | # cameras
> ## train | 15506 | 68672 | 1
> query | 1 | 2900 | 1
> gallery | 1 | 40466 | 1
> 
> using resnet101_ibn_a as a backbone
> Loading pretrained ImageNet model......from ./imagenet_models/resnet101_ibn_a.pth.tar
> using arcface with s:30, m: 0.4
> Traceback (most recent call last):
> File "test.py", line 44, in
> model.load_param(cfg.TEST.WEIGHT)
> File "/data/zhangting/NAIC_Person_ReID_DMT/model/make_model.py", line 157, in load_param
> self.state_dict()[i].copy_(param_dict[i])
> KeyError: 'module.base.conv1.weight'
> 请问这个报错是怎么回事呢

遇到了同样的错误，请问解决了吗

**Comment by heshuting555** [comment]
load的模型是多卡训练的模型，改成self.state_dict()[i.replace('module.', '')].copy_(param_dict[i])
即可
